<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>_2023</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Inputs\Day1.txt" />
    <None Remove="Inputs\Day10.txt" />
    <None Remove="Inputs\Day11.txt" />
    <None Remove="Inputs\Day12.txt" />
    <None Remove="Inputs\Day13.txt" />
    <None Remove="Inputs\Day14.txt" />
    <None Remove="Inputs\Day15.txt" />
    <None Remove="Inputs\day16.txt" />
    <None Remove="Inputs\Day17.txt" />
    <None Remove="Inputs\Day18.txt" />
    <None Remove="Inputs\Day19.txt" />
    <None Remove="Inputs\Day1_test.txt" />
    <None Remove="Inputs\Day2.txt" />
    <None Remove="Inputs\Day20.txt" />
    <None Remove="Inputs\Day21.txt" />
    <None Remove="Inputs\Day22.txt" />
    <None Remove="Inputs\Day23.txt" />
    <None Remove="Inputs\Day24.txt" />
    <None Remove="Inputs\Day3.txt" />
    <None Remove="Inputs\Day4.txt" />
    <None Remove="Inputs\Day5.txt" />
    <None Remove="Inputs\Day6.txt" />
    <None Remove="Inputs\Day7.txt" />
    <None Remove="Inputs\Day8.txt" />
    <None Remove="Inputs\Day9.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Inputs\Day12.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day13.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day14.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day15.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\day16.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day17.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day18.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day19.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day20.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day21.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day22.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day23.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day24.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day11.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day10.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day9.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day8.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day7.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day6.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day5.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day4.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day3.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day2.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day1_test.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Inputs\Day1.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
